matrix:
- name: javascript-typescript
  pipeline:
    - pyspelling.filters.javascript:
        jsdocs: true
        strings: true
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - en-custom.txt
    output: build/dictionary/python.dic
  glob_flags: N|G|B
  sources:
  - src/**/*.js
  - src/**/*.jsx
  - src/**/*.ts
  - src/**/*.tsx
- name: markdown
  aspell:
    lang: en
    d: en_US
    mode: markdown
  dictionary:
    wordlists:
    - en-custom.txt
    output: build/dictionary/python.dic
  sources:
  - README.md