matrix:
- name: javascript-typescript
  aspell:
    lang: en
    d: en_US
  glob_flags: N|G|B
  sources:
  - src/**/*.js
  - src/**/*.jsx
  - src/**/*.ts
  - src/**/*.tsx
- name: markdown
  aspell:
    lang: en
    d: en_US
    mode: markdown
  sources:
  - README.md