name: linting

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Install ESLint
        run: |
          npm install eslint@8.48.0

      - name: Run ESLint
        run: npx eslint .